# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
all:
  vars:
    single_node: true
    users:
      # @todo this is where you define which development team members have access to the server.
      # If you need to remove access from someone, do not remove them from this list, but instead set their state: absent
      - name: provision
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPBt8phtO8CEZbzXRDMZi3vTwkHEyUAR34/7aTgTM010qYIqBq0aFZODk6FPFi2xWpJQJYlz5+te9uVsb9PjvMJDIRaafgMMo1QlcYhYWdloQnqi4/pP5g7Fs/s9duwOwAE4SCAzxpYQTPXUupbwv9XlM5ulHyvoUSeGR4Q3q4iqTSXDdNuAHiHNTi7BAqFHjFma+om2/Wgb+RANT9bgL1RPF5sZlbGjRqrXMu+Q4nDv+mmLTwmdvOZVYvE71Jnlefkp1UzifCpiFTHZW5CMFFnxNFHJk49LFSntspt4am5KFOHfqbNaYA42dEupgK/RPY0Qev/w0GMB1bpP6EzGE6t7KP95AUXfjZoZOfOkE3Y03tBBX7+yzjVj3kiP3XASZCLqKxfUL1VZvjQ3sip/0ydagnpzu42qqft2S1VUq5bZfgotoJt/tWe0YkOfR8p3uRLBXNyn6rAQjxBZl8/p3uwdF2ttddUjfSHizf4eW+8kh9HFOyCvj9SKt1bnwbaNU= provision@crvs
        state: present
        sudoer: true
      - name: barry
        ssh_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICw4vvV33xxrTzxAiPoRhuwyWUzmgrP5NPo2n4bmKx7P
        state: present
        sudoer: true
    enable_backups: false
docker-manager-first:
  hosts:
    crvs: # @todo set this to be the hostname of your target server
      ansible_host: '124.43.177.246' # @todo set this to be the IP address of your server
      data_label: data1 # for manager machines, this should always be "data1"

# Development servers are not configured to use workers.
docker-workers: {}
