services:
  traefik:
    networks:
      - overlay_net
    command:
      # Use HTTP-01 challenge as the web server is publicly available
      # https://doc.traefik.io/traefik/https/acme/#httpchallenge
      # For DNS-01 challenge and manual certificates, check staging and production configurations
      - --certificatesresolvers.certResolver.acme.email=riku@opencrvs.org
      - --certificatesresolvers.certResolver.acme.storage=acme.json
      - --certificatesresolvers.certResolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.certResolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.certResolver.acme.httpchallenge=true

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.docker.swarmMode=true
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=WARNING
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --serverstransport.insecureskipverify=true
      - --entrypoints.websecure.address=:443
      - --accesslog=true
      - --accesslog.format=json
      - --ping=true

  notification:
    environment:
      - LANGUAGES=en,fr
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  countryconfig:
    image: ${DOCKERHUB_ACCOUNT}/${DOCKERHUB_REPO}:${COUNTRY_CONFIG_VERSION}
    restart: unless-stopped
    secrets:
      - jwt-public-key.{{ts}}
    environment:
      - NODE_ENV=production
      - QA_ENV=true
      - FHIR_URL=http://hearth:3447/fhir
      - AUTH_URL=http://auth:4040
      - APPLICATION_CONFIG_URL=http://config:2021
      - CONFIRM_REGISTRATION_URL=http://workflow:5050/confirm/registration
      - CHECK_INVALID_TOKEN=true
      - MONGO_URL=mongodb://mongo1/user-mgnt?replicaSet=rs0
      - SENTRY_DSN=${SENTRY_DSN:-}
      - SENDER_EMAIL_ADDRESS=${SENDER_EMAIL_ADDRESS}
      - ALERT_EMAIL=${ALERT_EMAIL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_SECURE=${SMTP_SECURE}
      - ESIGNET_REDIRECT_URL=https://esignet-mock.{{hostname}}/authorize
      - OPENID_PROVIDER_CLIENT_ID=mock-client_id
      - OPENID_PROVIDER_CLAIMS=name,family_name,given_name,middle_name,birthdate,address
      - MOSIP_API_USERINFO_URL=https://mosip-api.{{hostname}}/esignet/get-oidp-user-info
    deploy:
      replicas: 1
    networks:
      - overlay_net

  client:
    environment:
      - DECLARED_DECLARATION_SEARCH_QUERY_COUNT=100

  gateway:
    environment:
      - LANGUAGES=en,fr
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  workflow:
    environment:
      - LANGUAGES=en,fr
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  search:
    environment:
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  metrics:
    environment:
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  auth:
    environment:
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  user-mgnt:
    environment:
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  webhooks:
    environment:
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  config:
    environment:
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  documents:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  scheduler:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  mosip-api:
    volumes:
      - '/data/sqlite:/data/sqlite'
    image: ghcr.io/opencrvs/mosip-api:1.8.0
    environment:
      - NODE_ENV=production
      - MOSIP_BIRTH_WEBHOOK_URL=http://mosip-mock:20240/webhooks/opencrvs/birth
      - MOSIP_DEATH_WEBHOOK_URL=http://mosip-mock:20240/webhooks/opencrvs/death
      - OPENCRVS_GRAPHQL_GATEWAY_URL=http://gateway:7070/graphql
      - OPENCRVS_PUBLIC_KEY_URL=http://auth:4040/.well-known
      - LOCALE=en
      - ESIGNET_USERINFO_URL=http://esignet-mock:20260/oidc/userinfo
      - ESIGNET_TOKEN_URL=http://esignet-mock:20260/oauth/token
      - OIDP_CLIENT_PRIVATE_KEY_PATH=/certs/esignet-jwk.txt
      - OPENID_PROVIDER_CLAIMS=name,family_name,given_name,middle_name,birthdate,address
      - DECRYPT_P12_FILE_PATH=/certs/keystore.p12
      - DECRYPT_P12_FILE_PASSWORD=mosip123
      - ENCRYPT_CERT_PATH=/certs/ida-partner.crt
      - IDA_AUTH_DOMAIN_URI=http://mosip-mock:20240/
      - IDA_AUTH_URL=http://mosip-mock:20240/idauthentication/v1/auth
      - PARTNER_APIKEY=123456
      - PARTNER_ID=aaaaaAAAAAbbbbbBBBBBcccccCCCCCdddddDDDDD
      - PARTNER_MISP_LK=crvs-partner
      - SIGN_P12_FILE_PATH=/certs/keystore.p12
      - SIGN_P12_FILE_PASSWORD=mosip123
      - CLIENT_APP_URL=https://register.{{hostname}}
      - SQLITE_DATABASE_PATH=/data/sqlite/mosip-api.db
      - MOSIP_AUTH_URL=http://mosip-mock:20240/v1/authmanager/authenticate/clientidsecretkey
      - MOSIP_AUTH_CLIENT_APP_ID=admin
      - MOSIP_PACKET_AUTH_CLIENT_ID=mosip-regproc-client
      - MOSIP_PACKET_AUTH_CLIENT_SECRET=abcdeABCDE123456
      - MOSIP_WEBSUB_AUTH_CLIENT_ID=mosip-websub-client
      - MOSIP_WEBSUB_AUTH_CLIENT_SECRET=abcdeABCDE123456
      - MOSIP_WEBSUB_CALLBACK_URL=http://mosip-api:2024/websub/callback
      - MOSIP_WEBSUB_HUB_URL=http://mosip-mock:20240/websub/hub
      - MOSIP_WEBSUB_SECRET=mosip-websub-secret
      - MOSIP_WEBSUB_TOPIC=CREDENTIAL_ISSUED
      - MOSIP_CREATE_PACKET_URL=http://mosip-mock:20240/commons/v1/packetmanager/createPacket
      - MOSIP_PROCESS_PACKET_URL=http://mosip-mock:20240/registrationprocessor/v1/workflowmanager/workflowinstance
      - MOSIP_VERIFIABLE_CREDENTIAL_ALLOWLIST=http://mosip-mock:20240/.well-known/public-key.json
      - MOSIP_CENTER_ID=10123
      - MOSIP_MACHINE_ID=10234
    deploy:
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.mosip-api.rule=Host(`mosip-api.{{hostname}}`)'
        - 'traefik.http.services.mosip-api.loadbalancer.server.port=2024'
        - 'traefik.http.routers.mosip-api.tls=true'
        - 'traefik.http.routers.mosip-api.tls.certresolver=certResolver'
        - 'traefik.http.routers.mosip-api.entrypoints=web,websecure'
        - 'traefik.http.routers.mosip-api.middlewares=gzip-compression'
        - 'traefik.docker.network=opencrvs_overlay_net'
        - 'traefik.http.middlewares.mosip-api.headers.customresponseheaders.Pragma=no-cache'
        - 'traefik.http.middlewares.mosip-api.headers.customresponseheaders.Cache-control=no-store'
        - 'traefik.http.middlewares.mosip-api.headers.customresponseheaders.X-Robots-Tag=none'
        - 'traefik.http.middlewares.mosip-api.headers.stsseconds=31536000'
        - 'traefik.http.middlewares.mosip-api.headers.stsincludesubdomains=true'
        - 'traefik.http.middlewares.mosip-api.headers.stspreload=true'
    networks:
      - overlay_net
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://127.0.0.1:12201'
        tag: 'mosip-api'


  mosip-mock:
    image: ghcr.io/opencrvs/mosip-mock:1.8.0
    depends_on:
      - mosip-api
    environment:
      - NODE_ENV=production
      - SENDER_EMAIL_ADDRESS=${SENDER_EMAIL_ADDRESS:-}
      - ALERT_EMAIL=${ALERT_EMAIL:-}
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_PORT=${SMTP_PORT:-}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - SMTP_SECURE=${SMTP_SECURE:-}
      - MOSIP_WEBSUB_CALLBACK_URL=http://mosip-api:2024/websub/callback
      - ISSUER_URL=http://mosip-mock:20240
      - MOSIP_WEBSUB_TOPIC=CREDENTIAL_ISSUED
    networks:
      - overlay_net
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://127.0.0.1:12201'
        tag: 'mosip-mock'

  esignet-mock:
    image: ghcr.io/opencrvs/esignet-mock:1.8.0
    volumes:
      - /certs:/certs:ro 
    environment:
      - NODE_ENV=production
      - CLIENT_APP_URL=https://register.{{hostname}}
      - OIDP_CLIENT_PRIVATE_KEY_PATH=/certs/esignet-jwk.txt
    deploy:
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.esignet-mock.rule=Host(`esignet-mock.{{hostname}}`)'
        - 'traefik.http.services.esignet-mock.loadbalancer.server.port=20260'
        - 'traefik.http.routers.esignet-mock.tls=true'
        - 'traefik.http.routers.esignet-mock.tls.certresolver=certResolver'
        - 'traefik.http.routers.esignet-mock.entrypoints=web,websecure'
        - 'traefik.http.routers.esignet-mock.middlewares=gzip-compression'
        - 'traefik.docker.network=opencrvs_overlay_net'
        - 'traefik.http.middlewares.esignet-mock.headers.customresponseheaders.Pragma=no-cache'
        - 'traefik.http.middlewares.esignet-mock.headers.customresponseheaders.Cache-control=no-store'
        - 'traefik.http.middlewares.esignet-mock.headers.customresponseheaders.X-Robots-Tag=none'
        - 'traefik.http.middlewares.esignet-mock.headers.stsseconds=31536000'
        - 'traefik.http.middlewares.esignet-mock.headers.stsincludesubdomains=true'
        - 'traefik.http.middlewares.esignet-mock.headers.stspreload=true'
    networks:
      - overlay_net
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://127.0.0.1:12201'
        tag: 'esignet-mock'
